name: On Release Commit
on:
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      branch:
        type: string
        required: true

jobs:
  get-branches-to-propagate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: run ls command
      #   run: ls ${{ github.action_path }}
      # - name: get branches to propagate
      #   run: ${{ github.action_path }}/scripts/branchToPropagate.sh ${{ inputs.branch }}
      #   shell: bash
      - name: get branches to propagate
        run: >
          releaseBranches=$(git branch -r | grep 'release/' | tr -d 'origin/release/' | sort -n | xargs)\
          echo $releaseBranches

          # Replace " " by ","
          releaseBranches=$( echo ${releaseBranches// /","})

          echo $releaseBranches

          # get first param and remove "origin/release/"
          currentVersion=$(echo $INPUT_BRANCH | tr -d 'origin/release/')

          echo $currentVersion

          # Remove frist part of branch string 
          branchesToMerge=$( echo $releaseBranches | grep -oP "$currentVersion.*")

          # Remove current version from string
          branchesToMerge=$( echo ${branchesToMerge//$currentVersion/})

          # add "release/" for each version
          branchesToMerge=$( echo ${branchesToMerge//,/",release/"})

          # Concat with master
          branchesToMerge=$branchesToMerge","

          # add "release/" for each version
          branchesToMerge=$( echo ${branchesToMerge//,/"\",\""})

          # remove the the last two caracters (,")
          branchesToMerge=${branchesToMerge::-1}

          # remove the first caracter of string (",)
          branchesToMerge=${branchesToMerge#??}

          # Concat with master
          branchesToMerge=$branchesToMerge"\"master\""

          echo $branchesToMerge 

          branchesToMergeMTX=$(echo "[${branchesToMerge}]" | jq '.[]' )
          echo $branchesToMergeMTX 

          echo "BRANCHES_TO_MERGE_STR=[$branchesToMerge]" >> $GITHUB_OUTPUT
          echo "BRANCHES_TO_MERGE_MTX=$branchesToMergeMTX" >> $GITHUB_OUTPUT

        id: get-branches
      - name: Show branches to merge
        run: echo "The branches to merge  ${{ steps.get-branches.outputs.BRANCHES_TO_MERGE_STR }}"
      - name: Show branches to merge 2
        run: echo "The branches to merge  ${{ fromJson(steps.get-branches.outputs.BRANCHES_TO_MERGE_MTX) }}"
    outputs:
      branches-to-merge-str: ${{ steps.get-branches.outputs.BRANCHES_TO_MERGE_STR }}"
  propagate:
    needs: get-branches-to-propagate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        propagate-on: ${{ fromJson(needs.get-branches-to-propagate.outputs.branches-to-merge-str) }}
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ matrix.propagate-on }}
          github_token: ${{ secrets.TOKEN }}
          pr_label: "Automatic-PR,Release-Type" 